// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Script, console} from "forge-std/Script.sol";

contract DeployMiMCSponge is Script {
    /**
     * @notice Creates a minimal creation bytecode from a runtime bytecode THAT DOES NOT NEED CONSTRUCTOR ARGS.
     * @notice Consider the following example. Let L be the length of the runtime bytecode (consider for this simple example that L fits in 1 byte).
     *         0x    // Opcodes    | Stack
     *  [0x00] 60 80 // PUSH1 0x80 | 0x80
     *  [0x02] 60 40 // PUSH1 0x40 | 0x40 0x80
     *  [0x04] 52    // MSTORE     |
     *  [0x05] 60 L  // PUSH1 L    | L
     *  [0x07] 80    // DUP1       | L L
     *  [0x08] 60 11 // PUSH1 0x11 | 0x11 L L
     *  [0x0a] 60 00 // PUSH1 0x00 | 0x00 0x11 L L
     *  [0x0c] 39    // CODECOPY   | L
     *  [0x0d] 60 00 // PUSH1 0x00 | 0x00 L
     *  [0x0f] f3    // RETURN     |
     *  [0x10] fe    // INVALID
     *  [0x11]       // ... (the runtime bytecode comes here)
     *  In case L does not fit in 1 byte, instead of PUSH1 L, we use PUSH2 L, and instead of 0x11 we use 0x12. This function handles both cases.
     * @notice For more information, check: https://www.rareskills.io/post/ethereum-contract-creation-code
     * @param runtimeBytecode The runtime bytecode of the contract.
     * @return creationBytecode The creation bytecode of the contract.
     */
    function creationBytecodeFromRuntimeBytecode(bytes memory runtimeBytecode)
        internal
        pure
        returns (bytes memory creationBytecode)
    {
        require(runtimeBytecode.length <= 0x6000, "Runtime bytecode is larger than 24576 bytes");

        bytes2 runtimeCodeSize = bytes2(uint16(runtimeBytecode.length));
        bytes1 pushOpcodeUsed;
        bytes1 codeStartIdx;

        if (runtimeCodeSize & 0xff00 != 0) {
            pushOpcodeUsed = bytes1(uint8(0x61));
            codeStartIdx = bytes1(uint8(0x12));
        } else {
            pushOpcodeUsed = bytes1(uint8(0x60));
            codeStartIdx = bytes1(uint8(0x11));
        }

        creationBytecode = abi.encodePacked(
            bytes5(uint40(0x6080604052)),
            pushOpcodeUsed,
            runtimeCodeSize & 0xff00 != 0 ? runtimeCodeSize : bytes1(runtimeCodeSize),
            bytes2(uint16(0x8060)),
            codeStartIdx,
            bytes7(uint56(0x6000396000f3fe)),
            runtimeBytecode
        );
    }

    /**
     * @notice Deploys the MiMCSponge contract.
     * @notice The contract is deployed with the creation bytecode generated by the creationBytecodeFromRuntimeBytecode function.
     * @notice The runtime bytecode is exactly the same as the one present onchain and used in tornado cash (https://etherscan.io/address/0x83584f83f26af4edda9cbe8c730bc87c364b28fe#code)
     * @return deployed The address of the deployed contract.
     */
    function deployMimcSponge() internal returns (address deployed) {
        bytes memory creationBytecode = creationBytecodeFromRuntimeBytecode(
            vm.parseJsonBytes(vm.readFile("contracts/MiMCSponge_bytecode.json"), ".runtimeBytecode")
        );

        assembly {
            deployed := create(0, add(creationBytecode, 0x20), mload(creationBytecode))
            if iszero(deployed) { revert(0, 0) }
        }
    }

    function run() public virtual {
        vm.startBroadcast();
        address MimcSponge = deployMimcSponge();
        console.log("Deployed MimcSponge at:", MimcSponge);
        vm.stopBroadcast();
    }
}
